spring:
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"

server:
  port: 8081

logging:
  level:
    org.springframework.security: INFO
