spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=ordering
spring.datasource.username=user
spring.datasource.password=password

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.data-locations=classpath:sql/data.sql

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

#spring.sql.init.mode=never
#spring.sql.init.data-locations=
#spring.sql.init.schema-locations=
##spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password
spring.rabbitmq.virtual-host=/

# Optional: don?t fail on missing queues during dev
spring.rabbitmq.listener.simple.missing-queues-fatal=false
spring.rabbitmq.listener.direct.missing-queues-fatal=false

# JPA: avoid noisy drop errors
#spring.jpa.hibernate.ddl-auto=update

logging.level.sql=debug
logging.level.web=debug